DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS MEALS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE GLOBAL_SEQ START 100000;

CREATE TABLE USERS
(
    id INTEGER DEFAULT nextval('GLOBAL_SEQ') PRIMARY KEY,
    name VARCHAR,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    registered TIMESTAMP DEFAULT now(),
    enabled BOOL DEFAULT TRUE
);
CREATE UNIQUE INDEX "unique_email" ON USERS (email);

CREATE TABLE USER_ROLES
(
    user_id INTEGER NOT NULL,
    role VARCHAR,
    CONSTRAINT user_roles_fk FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_idx UNIQUE (user_id, role)
);

CREATE TABLE MEALS
(
    id INTEGER DEFAULT nextval('global_seq') PRIMARY KEY,
    description VARCHAR NOT NULL,
    date TIMESTAMP DEFAULT now(),
    calories INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT meals_fk FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);